# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpgenv < Formula
  desc ""
  homepage "https://github.com/notfromstatefarm/homebrew-gpgenv"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/notfromstatefarm/gpgenv/releases/download/v1.0.1/gpgenv_1.0.1_Darwin_arm64.tar.gz"
      sha256 "03ee75826794c95ad4cc5dd5fc5a5e6a3339a235b2a222c9bbbb4ce20aa686f9"

      def install
        bin.install "gpgenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/notfromstatefarm/gpgenv/releases/download/v1.0.1/gpgenv_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "32ce9f4ae77f75e0b11b077666317bee1643d95dd775e736a5e1587491b038b7"

      def install
        bin.install "gpgenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/notfromstatefarm/gpgenv/releases/download/v1.0.1/gpgenv_1.0.1_Linux_x86_64.tar.gz"
      sha256 "42983fef8e757e94ad498a00ee3b6f66b81f9bb2f1fb4c033e9912a32028df32"

      def install
        bin.install "gpgenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/notfromstatefarm/gpgenv/releases/download/v1.0.1/gpgenv_1.0.1_Linux_arm64.tar.gz"
      sha256 "a902c80e52f3fc0570c0173b1f28a16fd974868fc52713fd02284e7f5403ed34"

      def install
        bin.install "gpgenv"
      end
    end
  end

  depends_on "gpg"
end
