# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpgenv < Formula
  desc ""
  homepage "https://github.com/notfromstatefarm/homebrew-gpgenv"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/notfromstatefarm/gpgenv/releases/download/v1.0.0/gpgenv_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "838d992d52efede9cdf2b225786a70cb7709d9db3f1880ed47ab305961e18324"

      def install
        bin.install "gpgenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/notfromstatefarm/gpgenv/releases/download/v1.0.0/gpgenv_1.0.0_Darwin_arm64.tar.gz"
      sha256 "ecd3b0bcc7a47edc7aa69f42def4d3958d61771fc0cc2d60308f9c89b9b6ae42"

      def install
        bin.install "gpgenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/notfromstatefarm/gpgenv/releases/download/v1.0.0/gpgenv_1.0.0_Linux_arm64.tar.gz"
      sha256 "0e4c6354e140f4ec8378ab7ea9ae054fda556d0841bd786909c46d24c458a61b"

      def install
        bin.install "gpgenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/notfromstatefarm/gpgenv/releases/download/v1.0.0/gpgenv_1.0.0_Linux_x86_64.tar.gz"
      sha256 "b4f4e2a66e2fd1dac9aac9d4ad3ef521b8d95e9fa3be5b1147b5d1d2ca751ac6"

      def install
        bin.install "gpgenv"
      end
    end
  end
end
